pipeline {
    agent any
    stages {
        stage('zbuduj') {
            steps {
                echo 'buduję'
            }
            post {
                success {
                    echo 'zbudowano'
                }
            }
        }
        stage('przetestuj') {
            steps {
                echo 'testuję'
            }
        }
        stage('wdróż') {
            steps {
                echo 'wdrażam'
            }
        }
    }
    post {
        success {
            echo 'wdrożono'
        }
    }
}

